// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(SWDGradingDbContext))]
    [Migration("20251116151058_ChangeTeacherCodeToNullable")]
    partial class ChangeTeacherCodeToNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Entity.DocFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ExamStudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExamZipId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ParseMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ParsedText")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("ExamStudentId");

                    b.HasIndex("ExamZipId");

                    b.ToTable("doc_file", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Exam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExamPaper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("DATETIME");

                    b.HasKey("Id");

                    b.HasIndex("ExamCode")
                        .IsUnique();

                    b.ToTable("exam", (string)null);
                });

            modelBuilder.Entity("Model.Entity.ExamQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedDocSection")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("exam_question", (string)null);
                });

            modelBuilder.Entity("Model.Entity.ExamStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("exam_student", (string)null);
                });

            modelBuilder.Entity("Model.Entity.ExamZip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExtractedPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ParseSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("ZipName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ZipPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("exam_zip", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Grade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExamStudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("DATETIME");

                    b.Property<string>("GradedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExamStudentId");

                    b.ToTable("grade", (string)null);
                });

            modelBuilder.Entity("Model.Entity.GradeDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoDetectResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<long>("GradeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RubricId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Score")
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("RubricId");

                    b.ToTable("grade_detail", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Rubric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoCheckRule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Criterion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("ExamQuestionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExamQuestionId");

                    b.ToTable("rubric", (string)null);
                });

            modelBuilder.Entity("Model.Entity.SimilarityCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("DATETIME");

                    b.Property<int>("CheckedByUserId")
                        .HasColumnType("int");

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("DECIMAL(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("ExamId");

                    b.ToTable("similarity_check", (string)null);
                });

            modelBuilder.Entity("Model.Entity.SimilarityResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DocFile1Id")
                        .HasColumnType("bigint");

                    b.Property<long>("DocFile2Id")
                        .HasColumnType("bigint");

                    b.Property<long>("SimilarityCheckId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SimilarityScore")
                        .HasColumnType("DECIMAL(5,4)");

                    b.Property<string>("Student1Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Student2Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocFile1Id");

                    b.HasIndex("DocFile2Id");

                    b.HasIndex("SimilarityCheckId");

                    b.ToTable("similarity_result", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("Model.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TeacherCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Model.Entity.DocFile", b =>
                {
                    b.HasOne("Model.Entity.ExamStudent", "ExamStudent")
                        .WithMany()
                        .HasForeignKey("ExamStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.ExamZip", "ExamZip")
                        .WithMany()
                        .HasForeignKey("ExamZipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamStudent");

                    b.Navigation("ExamZip");
                });

            modelBuilder.Entity("Model.Entity.ExamQuestion", b =>
                {
                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Model.Entity.ExamStudent", b =>
                {
                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Model.Entity.ExamZip", b =>
                {
                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Model.Entity.Grade", b =>
                {
                    b.HasOne("Model.Entity.ExamStudent", "ExamStudent")
                        .WithMany("Grades")
                        .HasForeignKey("ExamStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamStudent");
                });

            modelBuilder.Entity("Model.Entity.GradeDetail", b =>
                {
                    b.HasOne("Model.Entity.Grade", "Grade")
                        .WithMany("Details")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.Rubric", "Rubric")
                        .WithMany()
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("Model.Entity.Rubric", b =>
                {
                    b.HasOne("Model.Entity.ExamQuestion", "ExamQuestion")
                        .WithMany("Rubrics")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("Model.Entity.SimilarityCheck", b =>
                {
                    b.HasOne("Model.Entity.User", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckedByUser");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Model.Entity.SimilarityResult", b =>
                {
                    b.HasOne("Model.Entity.DocFile", "DocFile1")
                        .WithMany()
                        .HasForeignKey("DocFile1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Entity.DocFile", "DocFile2")
                        .WithMany()
                        .HasForeignKey("DocFile2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Entity.SimilarityCheck", "SimilarityCheck")
                        .WithMany("SimilarityResults")
                        .HasForeignKey("SimilarityCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocFile1");

                    b.Navigation("DocFile2");

                    b.Navigation("SimilarityCheck");
                });

            modelBuilder.Entity("Model.Entity.Exam", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Model.Entity.ExamQuestion", b =>
                {
                    b.Navigation("Rubrics");
                });

            modelBuilder.Entity("Model.Entity.ExamStudent", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Model.Entity.Grade", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Model.Entity.SimilarityCheck", b =>
                {
                    b.Navigation("SimilarityResults");
                });
#pragma warning restore 612, 618
        }
    }
}
